name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.0", "3.1", "3.2", "3.3"]
        rails: ["61", "70", "71"]
    env:
      # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      # See https://github.com/ruby/setup-ruby/blob/master/README.md#matrix-of-gemfiles
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/Gemfile.rails${{ matrix.rails }}

    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: |
          bundle exec rake spec
        env:
          RAILS_ENV: test
